AWSTemplateFormatVersion: '2010-09-09'
Description: Nightwatch test results

Parameters:
  BucketName:
    Type: String
    Description: Name of the S3 Bucket to upload test results to


Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: Private
      BucketName: !Ref 'BucketName'
      Tags:
        - Key: Name
          Value: !Ref 'BucketName'
      VersioningConfiguration:
        Status: Enabled


Outputs:
  Bucket:
    Description: S3 Bucket
    Value: !Ref Bucket
