defaults: &defaults
  working_directory: ~/app
  docker:
    - image: rhinogram/selenium-chrome:latest

version: 2
jobs:
  canary-chrome:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Run Chrome Canary Tests
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              export LAUNCH_URL=https://app/rhinogram.com
            elif [ "$CIRCLE_BRANCH" == "staging" ]; then
              export LAUNCH_URL=https://staging.rhinogram.com
            else
              export LAUNCH_URL=https://dev.dev-rhinogram.com
            fi
            cd nightwatch_tests && BROWSER_NAME=chrome yarn canary
      - run:
          name: Deploy Test Results
          command: |
            yarn && node deploy
            aws s3 sync \
              nightwatch_tests/reports \
              s3://nightwatch-results-$CIRCLE_BRANCH \
              --acl public-read \
              --cache-control max-age=300 \
              --storage-class REDUCED_REDUNDANCY

  test:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Yarn
          command: yarn && (cd nightwatch_tests && yarn)
      - run:
          name: Lint
          command: cd nightwatch_tests && yarn eslint .


workflows:
  version: 2

  nightly:
    triggers:
      - schedule:
          cron: '0 5 * * *'
          filters:
            branches:
              only:
                - develop
    jobs:
      - canary-chrome

  merge:
    jobs:
      - canary-chrome:
          filters:
            branches:
              only:
                - develop

  general:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - develop
                - staging
                - master
