defaults: &defaults
  working_directory: ~/app
  docker:
    - image: rhinogram/selenium-chrome:latest

version: 2
jobs:
  updateECR:
    working_directory: ~/app
    docker:
      - image: node-awscli:8.11
    steps:
      - checkout
      - setup_remote_docker
      - run: yarn
      - run:
          name: Configure AWS CLI
          command: yarn rhinodeploy config
      - run:
          name: Get Env File
          command: yarn rhinodeploy envs -f e2e.env -l ./nightwatch_tests
      - run:
          name: Build and Upload Docker Image to ECR
          command: |
            docker build -t rhino-ecr/nightwatch nightwatch_tests
            # aws profile
            if [ "$CIRCLE_BRANCH" == "master" ] || [ "$CIRCLE_BRANCH" == "staging" ]; then
              profile=rhinoprod
            else
              profile=rhinodev
            fi
            # vars
            account=$(aws sts get-caller-identity --profile $profile | jq '.Account' | sed "s/\"//g")
            uri=$account.dkr.ecr.$AWS_REGION.amazonaws.com/rhino-ecr/nightwatch
            # tag the docker image to upload
            docker tag rhino-ecr/nightwatch $uri:$CIRCLE_BRANCH
            # login
            $(aws ecr get-login --no-include-email --profile $profile)
            # upload
            docker push $uri:$CIRCLE_BRANCH


  canary-chrome:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Run Chrome Canary Tests
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              export LAUNCH_URL=https://app.rhinogram.com
            elif [ "$CIRCLE_BRANCH" == "staging" ]; then
              export LAUNCH_URL=https://staging.rhinogram.com
            else
              export LAUNCH_URL=https://dev.dev-rhinogram.com
            fi
            cd nightwatch_tests
            yarn
            BROWSER_NAME=chrome yarn canary
      - store_test_results:
          path: ~/nightwatch-chrome
      - store_artifacts:
          path: ~/nightwatch-chrome

  lint:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Yarn
          command: yarn && (cd nightwatch_tests && yarn)
      - run:
          name: Lint
          command: cd nightwatch_tests && yarn eslint .


workflows:
  version: 2

  merge:
    jobs:
      - lint:
          filters:
            branches:
              only:
                - develop
      - canary-chrome:
          requires:
            - lint
          filters:
            branches:
              only:
                - develop
      - updateECR:
          requires:
            - canary-chrome
          filters:
            branches:
              only:
                - develop

  general:
    jobs:
      - lint:
          filters:
            branches:
              ignore:
                - develop
                - staging
                - master
