defaults: &defaults
  working_directory: ~/app
  docker:
    - image: rhinogram/selenium-chrome:latest

version: 2
jobs:
  canary:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:

  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run: 

workflows:
  version: 2


