defaults: &defaults
  working_directory: ~/app
  docker:
    - image: rhinogram/node-awscli:8.11

version: 2
jobs:
  buildAndUpdateEcr:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set region $AWS_REGION
            if [ "$CIRCLE_BRANCH" == "master" ] || [ "$CIRCLE_BRANCH" == "staging" ]; then
              aws configure set aws_access_key_id $RHINOPROD_ACCESS_KEY
              aws configure set aws_secret_access_key $RHINOPROD_SECRET_KEY
            else
              aws configure set aws_access_key_id $RHINODEV_ACCESS_KEY
              aws configure set aws_secret_access_key $RHINODEV_SECRET_KEY
            fi
      - run:
          name: Build Docker Image
          command: |
            docker build -t rhino-ecr/rhinomatic:nw-chrome -f nightwatch_tests/chrome.Dockerfile nightwatch_tests
      - run:
          name: Update ECR
          command: |
            # login
            $(aws ecr get-login --no-include-email)
            export accountId=$(aws sts get-caller-identity | jq '.Account' | sed "s/\"//g")
            baseUri=$accountId.dkr.ecr.$AWS_REGION.amazonaws.com/rhino-ecr/rhinomatic
            docker tag rhino-ecr/rhinomatic $baseUri:$CIRCLE_BRANCH-nw-chrome
            # push tagged with either "master-nw-chrome", "staging-nw-chrome", or "develop-nw-chrome"
            docker push $baseUri:$CIRCLE_BRANCH-nw-chrome
 
            if [ "$CIRCLE_BRANCH" == "master" ] || [ "$CIRCLE_BRANCH" == "develop" ]; then
              # always tag latest develop and master chrome builds with "latest"
              docker tag $baseUri:$CIRCLE_SHA1 $baseUri:latest
              docker push $baseUri:latest
            fi

  build:
    <<: *defaults
    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: docker build -f nightwatch_tests/chrome.Dockerfile nightwatch_tests

workflows:
  version: 2

  updateECR:
    jobs:
      - buildAndUpdateEcr:
          filters:
            branches:
              only:
                - master
                - staging
                - develop

  general:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
                - staging
                - develop
